services:
  - type: web
    name: image-gen-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend   
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
